/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: {
          DEFAULT: "#f1f5f9",
          muted: "#eef2f7",
        },
        brand: {
          DEFAULT: "#2563eb",
          hover: "#1d4ed8",
          active: "#1e40af",
          foreground: "#ffffff",
          muted: "#eff6ff",
          "muted-border": "#bfdbfe",
          light: "#dbeafe",
          50: "#eff6ff",
          100: "#dbeafe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
        shell: {
          sidebar: "#f8fafc",
          "sidebar-border": "#e2e8f0",
          "sidebar-hover": "#f1f5f9",
          nav: "#0f172a",
          "nav-muted": "#64748b",
          "nav-active-bg": "rgba(37, 99, 235, 0.085)",
          "nav-active-border": "#2563eb",
          "nav-section": "#9ca3af",
        },
        ink: { DEFAULT: "#0f172a", hover: "#1e293b" },
        surface: {
          DEFAULT: "#ffffff",
          muted: "#f8fafc",
          raised: "#ffffff",
          2: "#f8fafc",
          3: "#f1f5f9",
        },
        text: {
          primary: "#0f172a",
          secondary: "#475569",
          muted: "#64748b",
          placeholder: "#9ca3af",
        },
        border: {
          DEFAULT: "#e2e8f0",
          strong: "#cbd5e1",
          mid: "#d1d5db",
        },
        family: {
          atlas: "#2563eb",
          forge: "#d97706",
          relay: "#7c3aed",
          sentinel: "#dc2626",
          nexus: "#4b5563",
        },
        status: {
          pending: "#d97706",
          "pending-bg": "#fffbeb",
          "pending-border": "#fde68a",
          review: "#2563eb",
          "review-bg": "#eff6ff",
          "review-border": "#bfdbfe",
          approved: "#16a34a",
          "approved-bg": "#f0fdf4",
          "approved-border": "#bbf7d0",
          rejected: "#dc2626",
          "rejected-bg": "#fef2f2",
          "rejected-border": "#fecaca",
        },
        notice: {
          recommendation: "#d97706",
          "recommendation-bg": "#fffbeb",
          trending: "#16a34a",
          "trending-bg": "#f0fdf4",
          info: "#2563eb",
          "info-bg": "#eff6ff",
        },
        navy: { DEFAULT: "#111827" },
      },
      fontFamily: {
        sans: ["Inter", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        display: ["Inter", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "Consolas",
          "ui-monospace",
          "monospace",
        ],
      },
      fontSize: {
        "2xs": ["0.6875rem", { lineHeight: "1rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      },
      borderRadius: {
        sm: "6px",
        DEFAULT: "8px",
        md: "10px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        enterprise: "6px",
        "enterprise-md": "8px",
        "enterprise-lg": "12px",
        "enterprise-xl": "16px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(15, 23, 42, 0.06), 0 4px 12px rgba(15, 23, 42, 0.04)",
        "card-hover":
          "0 2px 4px rgba(15, 23, 42, 0.06), 0 8px 24px rgba(15, 23, 42, 0.08)",
        shell: "4px 0 20px rgba(15, 23, 42, 0.04)",
        inner: "inset 0 1px 2px rgba(15, 23, 42, 0.05)",
        topbar: "0 1px 0 rgba(15, 23, 42, 0.04), 0 4px 16px rgba(15, 23, 42, 0.04)",
        "card-md": "0 4px 6px rgba(0,0,0,0.04), 0 2px 4px rgba(0,0,0,0.06)",
        "card-lg": "0 10px 15px rgba(0,0,0,0.04), 0 4px 6px rgba(0,0,0,0.04)",
        enterprise: "0 1px 2px rgba(15,23,42,0.04), 0 1px 3px rgba(15,23,42,0.06)",
        "enterprise-md":
          "0 2px 4px rgba(15,23,42,0.04), 0 6px 12px rgba(15,23,42,0.06)",
      },
      animation: {
        pulse: "pulse 2s infinite",
        fadeIn: "fadeIn 0.2s ease-out",
        slideUp: "slideUp 0.2s ease-out",
        scaleIn: "scaleIn 0.15s ease-out",
        "bar-rise": "barRise 0.7s cubic-bezier(0.22, 1, 0.36, 1) both",
        "bar-fill": "barFill 0.58s cubic-bezier(0.22, 1, 0.36, 1) both",
      },
      keyframes: {
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: ".5" },
        },
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: {
          from: { transform: "translateY(8px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          from: { transform: "scale(0.97)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        barRise: {
          from: { transform: "scaleY(0)", opacity: "0.4" },
          to: { transform: "scaleY(1)", opacity: "1" },
        },
        barFill: {
          from: { transform: "scaleX(0)", opacity: "0.5" },
          to: { transform: "scaleX(1)", opacity: "1" },
        },
      },
      transitionDuration: { 180: "180ms" },
    },
  },
  plugins: [],
};
